<template>
    <AVTable :rows="data" :columns="headers">
        <template #body-cell-number="{ row }">
            <q-td> <AVButton :label="row.number" size="sm" /> </q-td>
        </template>
    </AVTable>
</template>

<script setup>
import AVTable from '@/atoms/AVTable.vue'
import AVButton from '@/atoms/AVButton.vue'

const headers = [
    {
        name: 'number',
        required: true,
        label: 'Flight No',
        align: 'left',
        field: (row) => row.number,
        format: (val) => `${val}`,
        sortable: true,
    },
    {
        name: 'aircraft',
        required: true,
        label: 'Aircraft',
        align: 'left',
        field: (row) => row.aircraft,
        format: (val) => `${val}`,
        sortable: true,
    },
    {
        name: 'date',
        required: true,
        label: 'Date',
        align: 'left',
        field: (row) => row.date,
        format: (val) => `${val}`,
        sortable: true,
    },
    {
        name: 'origin',
        required: true,
        label: 'Origin',
        align: 'left',
        field: (row) => row.origin,
        format: (val) => `${val}`,
        sortable: true,
    },
    {
        name: 'destination',
        required: true,
        label: 'Destination',
        align: 'left',
        field: (row) => row.destination,
        format: (val) => `${val}`,
        sortable: true,
    },
    {
        name: 'e',
        required: true,
        label: 'E',
        align: 'left',
        field: (row) => row.e,
        format: (val) => `${val}`,
        sortable: true,
    },
    {
        name: 'p',
        required: true,
        label: 'P',
        align: 'left',
        field: (row) => row.p,
        format: (val) => `${val}`,
        sortable: true,
    },
    {
        name: 'b',
        required: true,
        label: 'B',
        align: 'left',
        field: (row) => row.b,
        format: (val) => `${val}`,
        sortable: true,
    },
    {
        name: 'f',
        required: true,
        label: 'F',
        align: 'left',
        field: (row) => row.f,
        format: (val) => `${val}`,
        sortable: true,
    },
    {
        name: 'pet_lf',
        required: true,
        label: 'Pet LF %',
        align: 'left',
        field: (row) => row.pet_lf,
        format: (val) => `${val}`,
        sortable: true,
    },
    {
        name: 'd_to_d',
        required: true,
        label: 'D to D',
        align: 'left',
        field: (row) => row.d_to_d,
        format: (val) => `${val}`,
        sortable: true,
    },
    {
        name: 'revenue',
        required: true,
        label: 'Revenue',
        align: 'left',
        field: (row) => row.revenue,
        format: (val) => `${val}`,
        sortable: true,
    },
    {
        name: 'status',
        required: true,
        label: 'Status',
        align: 'left',
        field: (row) => row.status,
        format: (val) => `${val}`,
        sortable: true,
    },
]

const data = [
    {
        number: '123',
        aircraft: '736-600',
        date: '03 SEP 22',
        origin: 'CDG',
        destination: 'MIA',
        e: '2/2',
        p: '2/2',
        b: '1/2',
        f: '0/2',
        pet_lf: '75%',
        d_to_d: 12,
        revenue: '$600.00',
        status: 'ON TIME',
    },
    {
        number: '123',
        aircraft: '736-600',
        date: '03 SEP 22',
        origin: 'CDG',
        destination: 'MIA',
        e: '2/2',
        p: '2/2',
        b: '1/2',
        f: '0/2',
        pet_lf: '75%',
        d_to_d: 12,
        revenue: '$600.00',
        status: 'ON TIME',
    },
    {
        number: '123',
        aircraft: '736-600',
        date: '03 SEP 22',
        origin: 'CDG',
        destination: 'MIA',
        e: '2/2',
        p: '2/2',
        b: '1/2',
        f: '0/2',
        pet_lf: '75%',
        d_to_d: 12,
        revenue: '$600.00',
        status: 'ON TIME',
    },
    {
        number: '123',
        aircraft: '736-600',
        date: '03 SEP 22',
        origin: 'CDG',
        destination: 'MIA',
        e: '2/2',
        p: '2/2',
        b: '1/2',
        f: '0/2',
        pet_lf: '75%',
        d_to_d: 12,
        revenue: '$600.00',
        status: 'ON TIME',
    },
    {
        number: '123',
        aircraft: '736-600',
        date: '03 SEP 22',
        origin: 'CDG',
        destination: 'MIA',
        e: '2/2',
        p: '2/2',
        b: '1/2',
        f: '0/2',
        pet_lf: '75%',
        d_to_d: 12,
        revenue: '$600.00',
        status: 'ON TIME',
    },
    {
        number: '123',
        aircraft: '736-600',
        date: '03 SEP 22',
        origin: 'CDG',
        destination: 'MIA',
        e: '2/2',
        p: '2/2',
        b: '1/2',
        f: '0/2',
        pet_lf: '75%',
        d_to_d: 12,
        revenue: '$600.00',
        status: 'ON TIME',
    },
    {
        number: '123',
        aircraft: '736-600',
        date: '03 SEP 22',
        origin: 'CDG',
        destination: 'MIA',
        e: '2/2',
        p: '2/2',
        b: '1/2',
        f: '0/2',
        pet_lf: '75%',
        d_to_d: 12,
        revenue: '$600.00',
        status: 'ON TIME',
    },
]
</script>
